---
galaxy_info:
  author: ansible-starter Team
  description: Configuración común para todos los servidores / Common configuration for all servers
  company: ansible-starter
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - common
    - base
    - system

dependencies: []
