---
- name: Instalar fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Configurar jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: Restart fail2ban

- name: Habilitar y arrancar fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
